/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
uint32_t volatile* const rcc_ahb1enr = (uint32_t*) 0x40023830;
uint32_t volatile* const gpiod_mode = (uint32_t*)0x40020C00;
uint32_t volatile* const gpiod_pullup = (uint32_t*)0x40020C0C;
uint32_t volatile* const gpiod_input_data = (uint32_t*)0x40020C10;
uint32_t volatile* const gpiod_output_data = (uint32_t*)0x40020C14;
char pin_pressed = '0';
void delay(void)
{
	for(uint32_t i=0;i<300000;i++)
	{

	}
}
int main(void)
{
	//providing clock for port d
	*rcc_ahb1enr |= (1<<3);
//SETTING GPIO MODE
	//setting pin 0 (R1) as ouput
	*gpiod_mode |= (1<<0);
	*gpiod_mode &= ~(1<<1);
	//setting pin 1 (R2) as output
	*gpiod_mode |= (1<<2);
	*gpiod_mode &= ~(1<<3);
	//setting pin 2 (R3) as output
	*gpiod_mode |= (1<<4);
	*gpiod_mode &= ~(1<<5);
	//setting pin 3 (R4) as output
	*gpiod_mode |= (1<<6);
	*gpiod_mode &= ~(1<<7);

	//setting pin 8 (c1) as input
	*gpiod_mode &= ~(3<<16);
	//setting pin 9 (c2) as input
	*gpiod_mode &= ~(3<<18);
	//setting pin 10 (c3) as input
	*gpiod_mode &= ~(3<<20);
	//setting pin 11 (c4) as input
	*gpiod_mode &= ~(3<<22);

//SETTING PULLUP
//	//setting pin0(R1)  as pullup
//	gpiod_pullup |= (1<<0);
//	gpiod_pullup &= ~(1<<1);
//
//	//setting pin1(R2)  as pullup
//	gpiod_pullup |= (1<<2);
//	gpiod_pullup &= ~(1<<3);
//
//	//setting pin2(R3)  as pullup
//	gpiod_pullup |= (1<<4);
//	gpiod_pullup &= ~(1<<5);
//
//	//setting pin3(R4)  as pullup
//	gpiod_pullup |= (1<<6);
//	gpiod_pullup &= ~(1<<7);

   //setting pin8(C1)  as pullup
	*gpiod_pullup |= (1<<16);
	*gpiod_pullup &= ~(1<<17);

	//setting pin9(C2)  as pullup
	*gpiod_pullup |= (1<<18);
	*gpiod_pullup &= ~(1<<19);

	//setting pin10(C3)  as pullup
	*gpiod_pullup |= (1<<20);
	*gpiod_pullup &= ~(1<<21);

	//setting pin11(C4)  as pullup
	*gpiod_pullup |= (1<<22);
	*gpiod_pullup &= ~(1<<23);

	*gpiod_output_data |= (0x000F<<0);
    /* Loop forever */
	while(1)
	{
		*gpiod_output_data &= ~(1<<0);
		if((*gpiod_input_data & (1<<8))==0)
		{
			delay();

			pin_pressed = '1';
		}
		else if((*gpiod_input_data & (1<<9))==0)
		{
			delay();
			pin_pressed = '2';
		}
		else if((*gpiod_input_data & (1<<10))==0)
		{
			delay();

			pin_pressed = '3';
		}
		else if((*gpiod_input_data & (1<<11))==0)
		{
			delay();
			pin_pressed = 'A';

		}

		*gpiod_output_data |= (1<<0);
		*gpiod_output_data &= ~(1<<1);

		if((*gpiod_input_data & (1<<8))==0)
		{
		delay();
			pin_pressed = '4';
		}
		else if((*gpiod_input_data & (1<<9))==0)
		{
			delay();
			pin_pressed = '5';
		}
		else if((*gpiod_input_data & (1<<10))==0)
		{
			delay();
			pin_pressed = '6';
		}
		else if((*gpiod_input_data & (1<<11))==0)
		{
			delay();
			pin_pressed = 'B';
		}

		*gpiod_output_data |=(1<<1);
		*gpiod_output_data &= ~(1<<2);

		if((*gpiod_input_data & (1<<8))==0)
		{
			pin_pressed = '7';
		}
		else if((*gpiod_input_data & (1<<9))==0)
		{
			pin_pressed = '8';
		}
		else if((*gpiod_input_data & (1<<10))==0)
		{
			pin_pressed = '9';
		}
		else if((*gpiod_input_data & (1<<11))==0)
		{
			pin_pressed = 'C';
		}

		*gpiod_output_data |= (1<<2);
		*gpiod_output_data &= ~(1<<3);

		if((*gpiod_input_data & (1<<8))==0)
		{
			delay();
			pin_pressed = '*';
		}
		else if((*gpiod_input_data & (1<<9))==0)
		{
			delay();
			pin_pressed = '0';
		}
		else if((*gpiod_input_data & (1<<10))==0)
		{
			delay();
			pin_pressed = '#';
		}
		else if((*gpiod_input_data & (1<<11))==0)
		{
			delay();
			pin_pressed = 'D';
		}
		*gpiod_output_data |= (1<<3);
	}
}
